from models.referenciais import Idioma, Instituicao, TipoOuProfissao, ModalidadeEnsino, GrupoAcessos
from database.db import db


def send_referenciais():
    sends = {
        Idioma: 
        ["Português", "Inglês"],

        Instituicao: 
        ["COGNVOX",
        "Creche Alexandre dos Santos Oliveira",
        "Creche Denilma Bulhões",
        "Creche João Trajano dos Santos",
        "Creche Lúcia Nogueira",
        "Creche Maria Zenaide Rocha Santos",
        "Creche Menino Jesus",
        "Creche Professor Manoel Cecílio de Jesus",
        "Creche Rosete Andrade",
        "Creche Vovó Judith",
        "Curso Formação Psicólogos",
        "Escola Antônio Cândido Toledo",
        "Escola Barão de Penedo",
        "Escola Cláudio Daniel Gama Amorim",
        "Escola Côn. Teotônio Ribeiro",
        "Escola Dom Constantino Luers",
        "Escola Eng. Guttemberg Brêda Breda Netto",
        "Escola Fausto Ferreira Simões",
        "Escola Francisco Amálio Maria",
        "Escola Francisco Araújo Azevedo",
        "Escola General de Góes Monteiro",
        "Escola Hanna Bertholet",
        "Escola Irmã Jolenta",
        "Escola Isabel Cristina Alves Toledo",
        "Escola João XXIII",
        "Escola Josef Bergman",
        "Escola José Buarque da Silva",
        "Escola José de Carvalho Souza",
        "Escola Liege Gama Rocha",
        "Escola Manoel Tavares",
        "Escola Maria da Glória Pimenteira",
        "Escola Nossa Sra. do Mont Serrat",
        "Escola Paulo VI",
        "Escola Professor Arlindo Ferreira de Moraes",
        "Escola Professor Douglas Apratto Tenório",
        "Escola Professor Irênio Araújo",
        "Escola Professor Pedro Augusto Carneiro Leão",
        "Escola Professora Helena de O. de Carvalho",
        "Escola Professora Maria Rocha Santos Silva",
        "Escola Rotary",
        "Escola Santa Ana",
        "Escola Santa Cândida",
        "Escola Santa Luzia",
        "Escola Santa Sofia",
        "Escola Santa Terezinha",
        "Escola Santo Antônio",
        "Escola São João Batista",
        "Escola São Rafael",
        "ESCOLA TESTE",
        "Escola Ver. José da Costa Mangabeira",
        "Escola Ver. José Wilson Melo Nascimento",
        "Escola Ver. Manoel Soares de Melo",
        "Escola Wilton Lisboa Lucena"],

        TipoOuProfissao: 
        ["Assistente Pedagógico (ARIS)",
        "Assistente Social", 
        "Ator DI",
        "Aux. de Escritório",
        "Aux. de Limpeza",
        "Balconista",
        "Cozinheiro",
        "Embalador",
        "Estoquista",
        "Fonoaudióloga ",
        "Garçom",
        "Office-boy",
        "Outros",
        "Pai ou Responsável",
        "Par Interacional",
        "Pedagogo",
        "Professor",
        "Psicólogo",
        "Recepcionista",
        "Repositor",
        "Terapeuta"],

        ModalidadeEnsino: 
        ["Creche II-B-Tarde ",
        "1º Ano - A - Manhã ",
        "1º Ano - A - Tarde",
        "1º Ano - B - Manhã",
        "1º Ano - B - Tarde",
        "1º Ano - C - Tarde",
        "1º Ano - D - Tarde",
        "1º Ano - E - Tarde",
        "1º Ano-A-Manhã",
        "1º Ano-A-Tarde",
        "1º Ano-B-Manhã",
        "1º Ano-B-Tarde",
        "1º Ano-C-Tarde",
        "1º Ano-D-Tarde",
        "2º Ano - A - Manhã",
        "2º Ano - A - Tarde",
        "2º Ano - B - Manhã",
        "2º Ano - B - Tarde",
        "2º Ano - C - Manhã",
        "2º Ano - C - Tarde",
        "2º Ano - D - Tarde",
        "2º Ano - E - Manhã",
        "2º Ano - E - Tarde",
        "2º Ano-A-Manhã",
        "2º Ano-A-Tarde",
        "2º Ano-B-Manhã",
        "2º Ano-B-Tarde",
        "2º Ano-C-Tarde",
        "2º Ano-D-Tarde",
        "3º Ano  - A - Tarde",
        "3º Ano - A - Tarde",
        "3º Ano - A - Manhã",
        "3º Ano - B - Tarde",
        "3º Ano - B - Manhã",
        "3º Ano - D - Manhã",
        "3º Ano - C - Tarde",
        "3º Ano - D - Tarde",
        "3º Ano-A-Manhã",
        "3º Ano-A-Tarde",
        "3º Ano-B-Manhã",
        "3º Ano-B-Tarde",
        "3º Ano-C-Tarde",
        "4º Ano - A - Manhã",
        "4º Ano - A - Tarde",
        "4º Ano - B - Manhã",
        "4º Ano - B - Tarde",
        "4º Ano - C - Manhã",
        "4º Ano - C - Tarde",
        "4º Ano - D - Tarde",
        "4º Ano-A-Manhã",
        "4º Ano-A-Tarde",
        "4º Ano-B-Manhã",
        "4º Ano-B-Tarde",
        "4º Ano-C-Tarde",
        "4º Ano-D-Tarde",
        "4º Ano-E-Tarde",
        "5º Ano - A - Manhã",
        "5º Ano - A - Tarde",
        "5º Ano - B - Manhã",
        "5º Ano - B - Tarde",
        "5º Ano - C - Manhã",
        "5º Ano - C - Tarde",
        "5º Ano - D - Tarde",
        "5º Ano-A-Manhã",
        "5º Ano-A-Tarde",
        "5º Ano-B-Manhã",
        "5º Ano-B-Tarde",
        "5º Ano-C-Tarde",
        "5º Ano-D-Tarde",
        "6º Ano - A - Manhã",
        "6º Ano - A - Tarde",
        "6º Ano - B - Manhã",
        "6º Ano - B - Manhã",
        "6º Ano - B - Tarde",
        "6º Ano - C - Manhã",
        "6º Ano - C - Manhã",
        "6º Ano - C - Tarde",
        "6º Ano - D - Manhã",
        "6º Ano - D - Manhã",
        "6º Ano - D - Tarde",
        "6º Ano - E - Manhã",
        "6º Ano-A-Manhã",
        "6º Ano-A-Tarde",
        "6º Ano-B-Manhã",
        "6º Ano-B-Tarde",
        "6º Ano-C-Manhã",
        "6º Ano-C-Tarde",
        "6º Ano-D-Tarde",
        "6º Ano-E-Tarde",
        "7º Ano - A - Manhã",
        "7º Ano - A - Manhã",
        "7º Ano - A - Tarde",
        "7º Ano - B - Manhã",
        "7º Ano - B - Manhã",
        "7º Ano - B - Tarde",
        "7º Ano - C - Manhã",
        "7º Ano - C - Tarde",
        "7º Ano - D - Manhã",
        "7º Ano - D - Tarde",
        "7º Ano - E - Manhã",
        "7º Ano - F - Tarde",
        "7º Ano-A-Manhã",
        "7º Ano-A-Tarde",
        "7º Ano-B-Manhã",
        "7º Ano-B-Tarde",
        "7º Ano-C-Manhã",
        "7º Ano-C-Tarde",
        "7º Ano-D-Tarde",
        "7º Ano-E-Tarde",
        "8º Ano - A - Manhã",
        "8º Ano - A - Tarde",
        "8º Ano - B - Manhã",
        "8º Ano - B - Tarde",
        "8º Ano - C - Manhã",
        "8º Ano - C - Tarde",
        "8º Ano - D - Manhã",
        "8º Ano - D - Tarde",
        "8º Ano - E - Manhã",
        "8º Ano-A-Manhã",
        "8º Ano-A-Tarde",
        "8º Ano-B-Manhã",
        "8º Ano-C-Manhã",
        "8º Ano-D-Tarde",
        "8º Ano-E-Tarde",
        "9º Ano - A - Manhã",
        "9º Ano - A - Tarde",
        "9º Ano - A - Tarde",
        "9º Ano - B - Manhã",
        "9º Ano - B - Tarde",
        "9º Ano - C - Manhã",
        "9º Ano - C - Tarde1",
        "9º Ano - E - Tarde",
        "9º Ano-A-Manhã",
        "9º Ano-A-Tarde",
        "9º Ano-B-Manhã",
        "9º Ano-C-Tarde",
        "9º Ano-D-Tarde",
        "9º Ano-E-Tarde",
        "C2-A-Manhã",
        "C3-A-Tarde",
        "Creche I-A-Manhã",
        "Creche I-B-Manhã",
        "Creche II - A - Manhã",
        "Creche II - C - Tarde",
        "Creche II-A-Integra",
        " Creche II-A-Manhã",
        "Creche II-A-Tarde",
        "Creche II-C-Tarde",
        "Creche III - A - Manhã",
        "Creche III-A-Integral",
        "Creche III-A-Manhã",
        "Creche III-A-Tarde",
        "Creche III-B-Manhã",
        "Creche III-B-Tarde",
        "Creche III-C-Manhã",
        "EJA - A - Noite",
        "Jardim I - A - Manhã",
        "Jardim I - B - Manhã",
        "Jardim I - B - Manhã",
        "Jardim I - B - Manhã",
        "Jardim I - B - Manhã",
        "Jardim I - B - Manhã",
        "Jardim I - B - Tarde",
        "Jardim I - C - Tarde",
        "Jardim I-A-Integral",
        "Jardim I-A-Manhã",
        "Jardim I-A-Tarde",
        "Jardim I-B-Tarde",
        "Jardim II - A - Manhã",
        "Jardim II - A - Tarde",
        "Jardim II - B - Tarde",
        "Jardim II - C - Tarde",
        "Jardim II-A-Integral",
        "Jardim II-A-Manhã",
        "Jardim II-A-Tarde",
        "Jardim II-B-Tarde",
        "Jardim II-C-Tarde",
        "Maternal I - A - Integral",
        "Maternal I - B - Integral",
        "Maternal I-A-Manhã",
        "Maternal I-B-Tarde",
        "Maternal II - A - Integral",
        "Maternal II - A - Manhã",
        "Maternal II - B - Integral",
        "Maternal II - B - Manhã",
        "Maternal II - B - Tarde",
        "Maternal II - C - Manhã",
        "Maternal II-D-Manhã",
        "Maternal II-E-Tarde",
        "MODALIDADE COGNVOX",
        "Pré-Escola 1 - A - Manhã",
        "Pré-Escola 1 - C - Tarde",
        "Pré-Escola 1 - D - Tarde",
        "Pré-Escola 1 - E - Tarde",
        "Pré-Escola 1-A-Integral",
        "Pré-Escola 1-A-Manhã",
        "Pré-Escola 1-A-Tarde",
        "Pré-Escola 1-B-Manhã",
        "Pré-Escola 1-B-Tarde",
        "Pré-Escola 1-C-Manhã",
        "Pré-Escola 1-C-Tarde",
        "Pré-Escola 1-D-Tarde",
        "Pré-Escola 1-E-Tarde",
        "Pré-Escola 2 - A - Manhã",
        "Pré-Escola 2 - B - Tarde",
        "Pré-Escola 2 - C - Manhã",
        "Pré-Escola 2 - C - Tarde",
        "Pré-Escola 2 - D - Tarde",
        "Pré-Escola 2 - E - Tarde",
        "Pré-Escola 2-A-Manhã",
        "Pré-Escola 2-A-Tarde",
        "Pré-Escola 2-B-Manhã",
        "Pré-Escola 2-B-Tarde",
        "Pré-Escola 2-C-Tarde",
        "Pré-Escola 2-D-Tarde"],

        GrupoAcessos:
        ["Selecione o nível de acesso",
        "Administrador",
        "Administradores COGNVOX4 ",
        "Aluno DI5 ",
        "Aluno Interacional",
        "Aluno Profissional",
        "Apoio Técnico Pedagógico",
        "Assistente Pedagógico (ARIS)",
        "Assistente Social",
        "Coordenadora de Inclusão",
        "Coordenadores",
        "Estagiário Pedagogia",
        "Help Desk",
        "Pai ou Responsável",
        "Professores",
        "PSICOLOGOS_EAD15 ",
        "Psicólogo Supervisor",
        "Psicólogos",
        "Suporte"]
    }

    for modelo, nomes in sends.items():
        for nome in nomes:
            existente = modelo.query.filter_by(nome=nome).first()
            if not existente:
                registro = modelo(nome=nome)
                db.session.add(registro)

    db.session.commit()
    print("[SEND] Referenciais criados.")
